// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package walrus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WalrusClient is the client API for Walrus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalrusClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Walrus_SubscribeClient, error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type walrusClient struct {
	cc grpc.ClientConnInterface
}

func NewWalrusClient(cc grpc.ClientConnInterface) WalrusClient {
	return &walrusClient{cc}
}

func (c *walrusClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Walrus_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &Walrus_ServiceDesc.Streams[0], "/walrus.Walrus/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &walrusSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Walrus_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type walrusSubscribeClient struct {
	grpc.ClientStream
}

func (x *walrusSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *walrusClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/walrus.Walrus/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalrusServer is the server API for Walrus service.
// All implementations should embed UnimplementedWalrusServer
// for forward compatibility
type WalrusServer interface {
	Subscribe(*SubscribeRequest, Walrus_SubscribeServer) error
	Publish(context.Context, *PublishRequest) (*emptypb.Empty, error)
}

// UnimplementedWalrusServer should be embedded to have forward compatible implementations.
type UnimplementedWalrusServer struct {
}

func (UnimplementedWalrusServer) Subscribe(*SubscribeRequest, Walrus_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedWalrusServer) Publish(context.Context, *PublishRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}

// UnsafeWalrusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalrusServer will
// result in compilation errors.
type UnsafeWalrusServer interface {
	mustEmbedUnimplementedWalrusServer()
}

func RegisterWalrusServer(s grpc.ServiceRegistrar, srv WalrusServer) {
	s.RegisterService(&Walrus_ServiceDesc, srv)
}

func _Walrus_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WalrusServer).Subscribe(m, &walrusSubscribeServer{stream})
}

type Walrus_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type walrusSubscribeServer struct {
	grpc.ServerStream
}

func (x *walrusSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Walrus_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalrusServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walrus.Walrus/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalrusServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Walrus_ServiceDesc is the grpc.ServiceDesc for Walrus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Walrus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "walrus.Walrus",
	HandlerType: (*WalrusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _Walrus_Publish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Walrus_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "walrus.proto",
}
